// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gunuoqwcevmylcharzvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bnVvcXdjZXZteWxjaGFyenZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNDkzNTUsImV4cCI6MjA1MzgyNTM1NX0.xEW-op373Ose65bSyybKwN9I-MiRtuIAD_GGOXI_EJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);